### ISSUE TITLE
ICAP Client sending to much garbage bytes in case of small files

### ISSUE THREAD

**Issue by ajdergute** [toolarium/toolarium-icap-client#1]
First, thanks very much for this smart implementation of an ICAP-Client with Java. We want to use this client, but struggeling with our tests. To test a malicious file we use the well known EICAR-Testfile (https://www.eicar.org/?page_id=3950).

The client starts sending the file with a preview request. After the `100-continue` response. The remaining bytes are sent.
This client initializes a buffer of 8192 bytes. As the testfile is only 68 to 70 bytes long, the remaining bytes are sent, but garbage.

Our ICAP Server then sees a file of 8192+(Preview Bytes) size. As per specification the EICAR-Testfile must not exceed a file length of 128 bytes.

> The first 68 characters is the known string. It may be optionally appended by any combination of whitespace characters with the total file length not exceeding 128.

As a result our ICAP Server does not detect this testfile.

I suggest to initialize the buffer with the real bytes left for the actual file.

https://github.com/toolarium/toolarium-icap-client/blob/master/src/main/java/com/github/toolarium/icap/client/impl/ICAPClientImpl.java#L322

I'm able to come up with a PR for this.

**Comment by mepux** [comment]
Thanks for the detailed feedback. This issue is solved in v1.0.2 which new available. Please let me know if you still have issues.

**Comment by ajdergute** [comment]
Thanks a lot. Works like a charm
