### ISSUE TITLE
Use of SSL connection depending on the string "icaps:" from the icapUrl is not working....

### ISSUE THREAD

**Issue by QuaritschGerFfm** [toolarium/toolarium-icap-client#10]
Hey everyone,

during a test I noticed that when creating the ICAPClient via the method: 

`public ICAPClient getICAPClient(String icapUrl, int cacheMaxAgeInSeconds) throws MalformedURLException {...}`

the detection of an SSL connection (secureConnection) out of the icapUrl ist not working. The method creates always an unsecured connection :-( 

The reason is, that at this point:

https://github.com/toolarium/toolarium-icap-client/blob/c82042d274f0adb2b1fb96cb5e586cd49b9ba8bf/src/main/java/com/github/toolarium/icap/client/ICAPClientFactory.java#L166C36-L166C39

the wrong variable `url` is used, which is derived by substring from `icapUrl` and the leading string "icap:" or "icaps:" is not available any more. Using `icapUrl` instead of `url` at this point should fix the error.

Best regards,

**Comment by mepux** [comment]
Thanks for your feedback, version 1.3.4 fix this issue.

**Comment by mepux** [comment]
Thanks for your feedback, version 1.3.4 fix this issue.
