### ISSUE TITLE
It would be nice, to set the timeout for the creation of a Socket...

### ISSUE THREAD

**Issue by QuaritschGerFfm** [toolarium/toolarium-icap-client#11]
Hi @mepux,
actual there is no way to configure a timeout for the socket creation (connect), right?

It would be useful for tests with different invalid urls in the ci/cd pipeline.

I found this code where the Socket is created and later the connect() is executed, which allows to set a timeout which is always 0:

https://github.com/toolarium/toolarium-icap-client/blob/e23bceb417f8e17063cdaf8c5286416e273f951b/src/main/java/com/github/toolarium/icap/client/impl/ICAPConnectionManagerImpl.java#L46

But actual I found no way to set the timeout by using the normal Interface of your lib.
Furthermore I tried to set the vm property: -Dsun.net.client.defaultConnectTimeout=2000
which has no effect.

This would also be helpful for secure connections.

Do you see a possibility to add something in this regard?
If it is too time-consuming to offer the parameter to the outside as a parameter, a system property would come to mind. If it is not found, then the timeout = 0 (as today), otherwise the value in the system property. E.g. toolarium.icap.client.connectTimeout

Best regards,

**Comment by mepux** [comment]
On the ICAPConnectionManager there is new a method added to define the socket timeout based on the connection manager (>= v1.3.5):
    
    /**
     * Define the socket timeout
     *
     * @param timeout the socket timeout
     */
    void setSocketTimeout(int timeout);

**Comment by QuaritschGerFfm** [comment]
Hi @mepux,
sorry for my late reply and many thx for your support. We were on Christmas holidays and I was only able to test it this week.

Have you tested it? 

Two points I noticed:
- Setting the timeout has no effect. It always takes around 1 minute for the timeout to react
- the timeout is only implemented for ICAPS (secure socket) and not for ICAP. 

For us, this is a critical problem if the timeout is 1 minute long, because this would immediately trigger slow operation (Schwergang in German) in our services.

I may have some time this week to debug the problem (setting the timeout has no effect) in more detail.

Have a good start into the new year.
