### ISSUE TITLE
Wrong host in first part of header

### ISSUE THREAD

**Issue by cobaasta** [toolarium/toolarium-icap-client#13]
Hello, great library, but we have one issue with it:

According to the engineer who's responsible for Clearswift Secure ICAP Gateway, your library sets a wrong host in the first part of the header in the class ICAPClientImpl on line 344.
Instead of using the host name from the service information, the request source from the request information should be used:

```
String header = httpMethod + " /" + URLEncoder.encode(resource.getResourceName().trim(), StandardCharsets.UTF_8.name()) + " HTTP/1.1" + NEWLINE
                + "Host: " + requestInformation.getRequestSource() + NEWLINE + NEWLINE;
```

Greetings, Silvan Auer

**Comment by mepux** [comment]
It will be solved in next release (>=v1.3.5)
