### ISSUE TITLE
ICAPS support

### ISSUE THREAD

**Issue by ajdergute** [toolarium/toolarium-icap-client#2]
It would be nice if this icap client would support secure sockets for ICAPS. This would be a nice feature which is afaik not supported by other Java implementations.

What do you think about this?

**Comment by mepux** [comment]
Yes right, thanks for the feedback. Its already implemented and released as v1.1.0. To handle specific requirements regarding SSL connection a ICAPConnectionManager can be overwritten and set on the ICAPClientFactory. This should give in a simple way enough flexibility.
