### ISSUE TITLE
Tipo in exception and log message

### ISSUE THREAD

**Issue by tspoeri** [toolarium/toolarium-icap-client#7]
The message that is used for the log and in the exception that is raised if a threat is found starts like that: `Thread found in resource ...`.
Correct is "Threat" with a **'t'** at the end instead of a 'd'.

Can you please fix that in the client and in the readme (in the example log output)

**Comment by mepux** [comment]
Thanks, it's adapted.

**Comment by mepux** [comment]
Resolved in release v1.2.0
