### ISSUE TITLE
Bad chunk header error on empty lines in text files

### ISSUE THREAD

**Issue by maciejborkowski** [toolarium/toolarium-icap-client#9]
Hello

I have encountered an issue where, for a simple text file, an empty line produces an error on REQMOD request.

For a file that starts with a newline and in next line "testtext" string it can look like this:

> java.io.IOException: Bad chunk header [        testtext]:For input string: "testtext" under radix 16

For a file that contains only a newline:

> java.io.IOException: Bad chunk header []:For input string: "" under radix 16]

Is this a bug or I am misusing the library?

**Comment by mepux** [comment]
The size of the input resource of the object ICAPResource must properly match. Additionally, there was an issue by zero file size. This is solved in v1.3.2 which is released (rollout to maven takes a while).
